version: '3.4'

services:
  distancecalculatorbackend:
    image: distancecalculatorbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
